### ISSUE TITLE
Japanese Volume 2 seed

### ISSUE THREAD

**Issue by zeldapunkgrrl** [czarchasm00/czarchasm00.github.io#1]
Would it be possible to get a seed for japanese volume 2?

**Comment by czarchasm00** [comment]
Fixed after updating the system. I was able to download via VPN without issue. Try now and let me know how it goes.

**Comment by zeldapunkgrrl** [comment]
Seems to be working now. Thanks

**Comment by czarchasm00** [comment]
It should be working again now. There was an internet outage in my area. Comcast is shit. Try again lol. Sorry

**Comment by zeldapunkgrrl** [comment]
Thank you. Was finally able to finish downloading.
